config/routes.rb
Poker::Application.routes.draw do
  get "tables", to: "tables#index"
  get "table", to: "tables#table"

  resource :sessions, only: [:new, :create, :destroy]
  
  resources :users
    
  get '', to: "poker#index"
      
  get 'index', to: "poker#index"

  get "register", to: "users#register"

  post "confirm_registration_user", to: "users#confirm_registration"
  
  post "confirm_creation_table", to: "tables#confirm_creation_table"

  get 'signout', to: "poker#sign_out"
  
  match '/signin', to: 'sessions#new', via: 'get'
  
  match '/signup',  to: 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  get '/notification', to: 'sessions#notification'
  
  ##########
  ##########
  ##########
  match '/send_message', to: 'tables#process_message'
  
  match '/get_messages', to: 'tables#get_messages'
  ##########
  ##########
  ##########
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
#  layout false, :except => :index
  
  def index
    gC = GameController.instance
    @tables = GameController.getRooms
    respond_to do |format|
      format.html
      format.json { render json: @tables }
    end
  end
  
  def create
    @table = Table.new
  end

  def confirm_creation_table

    s = get_session
    if s == nil
      @notice = "your session is expired"
      redirect_to index_path
      return
    end


#    t = Table.where(:session_id => s.id)
#    if t.length != 0
#      @notice = "you can not create more than one table"
#      redirect_to tables_path
#      return
#    end
    
    #gC = GameController.instance  
#    table = Table.new
#    table.name = params[:table][:name]
    
    if GameController.addRoom(params[:table][:name], s.id)
      redirect_to table_path+"?name="+params[:table][:name]
      return
    else
      respond_to do |format|
        format.html { redirect_to(index_path, :notice => "table is not created")}
        format.xml { head :ok}
      end
    end
    
  end
  
  def table
    s = get_session
    if s == nil
      @notice = "your session is expired"
      redirect_to index_path
      return
    end

    #gC = GameController.instance  

    @table_name = params[:name]
    
    @tables = GameController.getRooms
    valid_name = false
    @tables.each do |table|
      if table == @table_name
        valid_name = true
      end
    end
    if not valid_name
      redirect_to tables_path
    end
    #gC = GameController.instance 
    @table_name = params[:name]
    @messages = GameController.getMessages(s.id, @table_name)

  end
  
  def process_message
    s = get_session
    if s == nil
      @notice = "your session is expired"
      redirect_to index_path
      return
    end
    gC = GameController.instance 
    @message = params[:message]
    @table_name = params[:name]
    logger.debug ">>>>>>>>>>>>>>>>>>>>"
      logger.debug "roomId " + @table_name
      logger.debug "messages" + @message
    logger.debug ">>>>>>>>>>>>>>>>>>>>"

    GameController.sendMessage(s.id, @table_name, @message)
    render "send_message", :layout => false
  end 
        
  def get_messages
    s = get_session
    if s == nil
      @notice = "your session is expired"
      redirect_to index_path
      return
    end
    gC = GameController.instance 
    @table_name = params[:name]
    @messages = GameController.getMessages(s.id, @table_name)

    logger.debug "-------------------------------------------------------"


      logger.debug "messages " + @messages
      render :layout => false
      #render "get_messages"
    
    
    logger.debug "-------------------------------------------------------"
    
    return @messages
#    respond_to do |format|
#      format.js {render :json => "ss".to_json }
#    end
    
  end    
    
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_create.html.erb
<div class="create_user_form">
	<%= form_for :table, :url => confirm_creation_table_path do |f|%>
	<fieldset>
		<div>
			<%= f.label :name%>:
			<%= f.text_field :name%>
		</div>
		<div>
			<%= f.submit "Create"%>
		</div>	</fieldset>
	<% end %>
</div>	

app/views/tables/_index.html.erb
<%
if @tables.length == 0
%>
<p>there is no tables for you</p>
<%
else
%>

<table class = "table_tables">
	<tr>
		<th>Tables</th>		
	</tr>	
	<% @tables.each do |t| %>
	<tr>
		<td><%= link_to t, table_path+"?name="+t%></td>
	</tr>
	<% end %>
</table>
<%
end
%>

app/views/tables/get_messages.html.erb
This is needless text. I include it to figure out does work my respond to jquery request.
As a result it works!!!!! I fall in love with rails.

I type to make changes for new commit.
<br>

app/views/tables/index.html.erb
<%= render 'tables/index'%>

<%if signed_in?%>
<%= render 'tables/create'%>
<%end%>

app/views/tables/table.html.erb
<h1>Tables#table</h1>

<p><%=	@table_name %></p>

<p>
<%=
	@messages
%>
</p>

<script type = "text/javascript">
	function sendMessage() {
		$.get(
			'<%= send_message_path %>',
			{
				name:'<%= @table_name%>',
				message: document.getElementById('MessageToSend').value
			}
		)
	}

	function getMessages() {
		$.get(
			'<%= get_messages_path %>',
			{
				name:'<%= @table_name%>',
			},
			onGetMessagesSucess
		);
	}

	function onGetMessagesSucess(data) {
		document.getElementById('Messages').value = data;
	}
	
</script>
<%
if signed_in?
%>

	<textarea id = 'Messages'></textarea>
	<button onClick = 'getMessages()'>Get Messages</button>
	<textarea id = 'MessageToSend'></textarea>
	<button onClick = 'sendMessage()'>Send Message</button>

<%
end
%>