config/routes.rb
Poker::Application.routes.draw do
  get "tables", to: "tables#index"
  get "table", to: "tables#table"

  resource :sessions, only: [:new, :create, :destroy]
  
  resources :users
    
  get '', to: "poker#index"
      
  get 'index', to: "poker#index"

  get "register", to: "users#register"

  post "confirm_registration_user", to: "users#confirm_registration"
  
  post "confirm_creation_table", to: "tables#confirm_creation_table"

  get 'signout', to: "poker#sign_out"
  
  match '/signin', to: 'sessions#new', via: 'get'
  
  match '/signup',  to: 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  get '/notification', to: 'sessions#notification'
  
  ##########
  ##########
  ##########
  match '/send_message', to: 'tables#process_message'
  
  match '/get_messages', to: 'tables#get_messages'
  ##########
  ##########
  ##########
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://rubyonrails.org/">Ruby on rails</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <!--<li><%= link_to "Contact", '#' %></li> -->
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Poker", '/index', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
          	<li><%= link_to 'Register', register_path%></li>
          	<li><%= link_to "Tables", tables_path%></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_push_notification.html.erb
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script type = "text/javascript">

	function sendGetRequest() {
		$.get(
			"<%= notification_path %>"			
		);
	}
	
<%
if signed_in?
%>
	setInterval("sendGetRequest()", 15000);
<%
else
%>
//	alert("aaaa");
<%
end
%>
</script>
		<button onClick = "sendGetRequest()">SendRequest</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'layouts/push_notification'%>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>

</body>
</html>